version: "3.7"
x-common-variables:
  &common-vars
  MYSQL_DATABASE: fullstack
  MYSQL_USER: user
  MYSQL_PASSWORD: pass

volumes:
  db:


services:
  db:
    image: mysql:5.7
    container_name: db
    expose:
      - 3306
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    environment:
      <<: *common-vars
      MYSQL_ROOT_PASSWORD: password

  back:
    build:
      context: backend
      dockerfile: Dockerfile
    depends_on:
      - db
    container_name: back
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      <<: *common-vars
      MYSQL_HOST: 'db'
      MYSQL_PORT: '3306'

    restart: on-failure

  front:
    build:
      context: frontend
      dockerfile: Dockerfile
    depends_on:
      - back
    expose:
      - 3000
    ports:
      - 3000:3000
    container_name: front
    restart: on-failure
