version: "3.7"
x-common-variables:
  &common-vars
  MYSQL_DATABASE: fullstack
  MYSQL_USER: user
  MYSQL_PASSWORD: pass

volumes:
  db:

networks:
  internal:
  external:

services:
  db:
    image: mysql:5.7
    container_name: db
    expose:
      - 3306
    volumes:
      - db:/var/lib/mysql
    environment:
      <<: *common-vars
      MYSQL_ROOT_PASSWORD: password
    networks:
      - internal

  back:
    build:
      context: backend
      dockerfile: Dockerfile
    depends_on:
      - db
    container_name: back
    expose:
      - 8080
    environment:
      <<: *common-vars
      MYSQL_HOST: 'db'
      MYSQL_PORT: '3306'
    restart: on-failure
    networks:
      - internal

  front:
    build:
      context: frontend
      dockerfile: Dockerfile
    depends_on:
      - back
    expose:
      - 3000
    container_name: front
    restart: on-failure
    networks: 
      - internal
  
  proxy:
    build:
      context: nginx
      dockerfile: Dockerfile
    depends_on:
      - front
      - back
    ports:
      - 80:80
    restart: on-failure
    networks:
      - internal
      - external